//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropDownValue
    {
        public int DropDownValueID { get; set; }
        public int DropDownID { get; set; }
        public string Value { get; set; }
    
        public virtual DropDown DropDown { get; set; }
    }
}
