//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyValues = new HashSet<PropertyValue>();
        }
    
        public int PropertyID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public Nullable<int> DropDownID { get; set; }
        public int AssetTypeID { get; set; }
    
        public virtual AssetType AssetType { get; set; }
        public virtual DropDown DropDown { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyValue> PropertyValues { get; set; }

        public PropertyBare getPropertyBare()
        {
            PropertyBare propertyBare = new PropertyBare();
            propertyBare.PropertyID = this.PropertyID;
            propertyBare.Name = this.Name;
            propertyBare.Type = this.Type;
            propertyBare.Unit = this.Unit;
            propertyBare.DropDownID = this.DropDownID;
            propertyBare.AssetTypeID = this.AssetTypeID;
            return propertyBare;
        }
    }

    public class PropertyBare
    {
        public int PropertyID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Unit { get; set; }
        public Nullable<int> DropDownID { get; set; }
        public int AssetTypeID { get; set; }
    }
}
