//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyValue
    {
        public int PropertyValueID { get; set; }
        public int AssetID { get; set; }
        public int PropertyID { get; set; }
        public string Value { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Property Property { get; set; }
    }
}
